import { createAdminClient } from "@/lib/supabase/server"
import { deductCredits } from "@/lib/credits"
import { startQualificationCall } from "@/lib/voice/start-qualification-call"
import { applyProspectTransition, type ProspectEvent } from "@/lib/outreach/prospect-state-machine"
import { inngest } from "@/inngest/client"
import crypto from "node:crypto"
import { phoneHash } from "@/lib/voice-compliance"
export { nextScheduleOccurrence } from "@/lib/outreach/schedule"

export type OutreachChannel = "email" | "voice" | "smart_both"
export type LeadSearchFilters = { lead_status?: string; has_email?: boolean; has_phone?: boolean; limit?: number }
export type DispatchOutreachInput = { userId:string; requestedBy:"ui"|"chat"|"schedule"|"system"; channel:OutreachChannel; prospectIds?:string[]; filters?:LeadSearchFilters; scheduleId?:string; approvalId:string; idempotencyKey:string; dryRun?:boolean }
export type OutreachRunResult = { runId?:string; status:"preview"|"pending"|"running"|"completed"|"partial"|"failed"; eligible:number; skipped:number; estimatedCredits:number; items?:Array<{prospectId:string; channel:"email"|"voice"; status:string; reason?:string}>; error?:string }

type Lead = { id:string; email:string|null; phone:string|null; lead_status:string|null; email_subject:string|null; email_body:string|null }
const terminal = new Set(["qualified","disqualified","converted","do_not_contact"])

export async function dispatchAutonomousOutreach(input: DispatchOutreachInput): Promise<OutreachRunResult> {
  const db = createAdminClient(); const strategy=input.channel
  let q=db.from("prospects").select("id,email,phone,lead_status,email_subject,email_body").eq("user_id",input.userId).limit(Math.min(input.filters?.limit ?? 100,100))
  if(input.prospectIds?.length) q=q.in("id",input.prospectIds.slice(0,100)); else if(input.filters?.lead_status && input.filters.lead_status!=="any") q=q.eq("lead_status",input.filters.lead_status)
  const {data}=await q; const leads=(data??[]) as Lead[]
  const items:Array<{prospectId:string;channel:"email"|"voice";status:string;reason?:string}>=[]
  for(const lead of leads){
    if(terminal.has(lead.lead_status??"new")){ items.push({prospectId:lead.id,channel:"email",status:"skipped",reason:"terminal_lead_status"}); continue }
    const [{data:active},{data:emailSuppressed},{data:phoneSuppressed}]=await Promise.all([db.from("outreach_run_items").select("id").eq("user_id",input.userId).eq("prospect_id",lead.id).in("status",["pending","claimed","queued","scheduled"]).limit(1).maybeSingle(),lead.email?db.from("suppressions").select("email_hash").eq("user_id",input.userId).eq("email_hash",crypto.createHash("sha256").update(lead.email.trim().toLowerCase()).digest("hex")).maybeSingle():Promise.resolve({data:null}),lead.phone?db.from("phone_suppressions").select("id").eq("user_id",input.userId).eq("phone_hash",phoneHash(lead.phone)).in("channel",["voice","all"]).maybeSingle():Promise.resolve({data:null})])
    if(strategy!=="voice") items.push({prospectId:lead.id,channel:"email",status:lead.email&&!active&&!emailSuppressed?"eligible":"skipped",...(!lead.email?{reason:"missing_email"}:active?{reason:"already_claimed"}:emailSuppressed?{reason:"suppressed_email"}:{})})
    if(strategy!=="email") items.push({prospectId:lead.id,channel:"voice",status:lead.phone&&!active&&!phoneSuppressed?"eligible":"skipped",...(!lead.phone?{reason:"missing_phone"}:active?{reason:"already_claimed"}:phoneSuppressed?{reason:"suppressed_phone"}:{})})
  }
  const eligible=items.filter(x=>x.status==="eligible").length, skipped=items.length-eligible, estimatedCredits=eligible ? 1 : 0
  if(input.dryRun) return {status:"preview",eligible,skipped,estimatedCredits,items}
  const {data: approval}=await db.from("outreach_action_approvals").select("id,action_kind,channel,scope,consent_attestation,consumed_at,expires_at,confirmed_at,user_id").eq("id",input.approvalId).eq("user_id",input.userId).maybeSingle()
  const scope=(approval?.scope??{}) as {channel?:string;prospectIds?:unknown[];filters?:unknown;input?:{lead_id?:string}}
  const requestedIds=[...(input.prospectIds??[])].map(String).sort()
  const approvedIds=Array.isArray(scope.prospectIds)?scope.prospectIds.map(String).sort():[]
  const isFollowup=approval?.action_kind==="lead_followup"&&requestedIds.length===1&&scope.input?.lead_id===requestedIds[0]
  const isOutreach=approval?.action_kind==="autonomous_outreach"&&scope.channel===strategy&&JSON.stringify(approvedIds)===JSON.stringify(requestedIds)&&JSON.stringify(scope.filters??null)===JSON.stringify(input.filters??null)
  const consent=(approval?.consent_attestation??{}) as {confirmed?:boolean}
  const scheduleOwned=input.scheduleId?await db.from("outreach_schedules").select("id").eq("id",input.scheduleId).eq("user_id",input.userId).eq("approval_id",input.approvalId).maybeSingle():null
  if(!approval || (!isOutreach&&!isFollowup) || (!input.scheduleId&&approval.consumed_at) || !approval.confirmed_at || ((strategy==="voice"||strategy==="smart_both")&&!consent.confirmed) || (!input.scheduleId&&approval.expires_at&&new Date(String(approval.expires_at))<=new Date()) || (input.scheduleId&&!scheduleOwned?.data)) return {status:"failed",eligible,skipped,estimatedCredits,error:"A current, action-specific, scoped outreach approval is required."}
  const effectiveIdempotencyKey=input.scheduleId?input.idempotencyKey:`approval:${input.approvalId}`
  const {data: existing}=await db.from("outreach_runs").select("id,status,requested_count,skipped_count,platform_credits_charged").eq("user_id",input.userId).eq("idempotency_key",effectiveIdempotencyKey).maybeSingle()
  if(existing) return {runId:String(existing.id),status:String(existing.status) as OutreachRunResult["status"],eligible:Number(existing.requested_count)-Number(existing.skipped_count),skipped:Number(existing.skipped_count),estimatedCredits:Number(existing.platform_credits_charged)}
  const {data: run,error}=await db.from("outreach_runs").insert({user_id:input.userId,schedule_id:input.scheduleId??null,triggered_by:input.requestedBy,channel_strategy:strategy,status:"running",approval_id:input.approvalId,idempotency_key:effectiveIdempotencyKey,requested_count:items.length,skipped_count:skipped,lead_filter:input.filters??{},config_snapshot:{strategy}}).select("id").single()
  if(error||!run){const {data: raced}=await db.from("outreach_runs").select("id,status,requested_count,skipped_count,platform_credits_charged").eq("user_id",input.userId).eq("approval_id",input.approvalId).is("schedule_id",null).maybeSingle();if(raced)return {runId:String(raced.id),status:String(raced.status) as OutreachRunResult["status"],eligible:Number(raced.requested_count)-Number(raced.skipped_count),skipped:Number(raced.skipped_count),estimatedCredits:Number(raced.platform_credits_charged)};return {status:"failed",eligible,skipped,estimatedCredits,error:error?.message??"Could not create outreach run."}}
  if(!input.scheduleId){const {data:consumed}=await db.from("outreach_action_approvals").update({consumed_at:new Date().toISOString()}).eq("id",input.approvalId).eq("user_id",input.userId).is("consumed_at",null).select("id").maybeSingle();if(!consumed){await db.from("outreach_runs").update({status:"failed",error:"Approval was already consumed."}).eq("id",run.id).eq("user_id",input.userId);return {runId:run.id,status:"failed",eligible,skipped,estimatedCredits,error:"Approval was already consumed."}}}
  if(eligible){ const charge=await deductCredits({userId:input.userId,count:estimatedCredits,reason:"autonomous_outreach_orchestration",idempotencyKey:`run:${run.id}:orchestration`}); if(!charge.ok){ await db.from("outreach_runs").update({status:"failed",error:charge.error}).eq("id",run.id).eq("user_id",input.userId); return {runId:run.id,status:"failed",eligible,skipped,estimatedCredits,error:charge.error} }; await db.from("outreach_runs").update({platform_credits_charged:estimatedCredits}).eq("id",run.id).eq("user_id",input.userId) }
  await db.from("outreach_run_items").insert(items.map((x,i)=>({user_id:input.userId,run_id:run.id,prospect_id:x.prospectId,channel:x.channel,step_order:strategy==="smart_both"&&x.channel==="voice"?1:0,status:x.status==="eligible"?"pending":"skipped",skip_reason:x.reason??null,scheduled_for:strategy==="smart_both"&&x.channel==="voice"?new Date(Date.now()+86400000).toISOString():new Date().toISOString(),idempotency_key:`${run.id}:${x.prospectId}:${x.channel}:${i}`})))
  await inngest.send({name:"outreach/run.requested",data:{runId:String(run.id),userId:input.userId}}); return {runId:String(run.id),status:"pending",eligible,skipped,estimatedCredits}
}

export async function executeOutreachRun(runId:string,userId:string):Promise<void>{
 const db=createAdminClient(); const {data:run}=await db.from("outreach_runs").select("approval_id").eq("id",runId).eq("user_id",userId).maybeSingle();if(!run)return;const {data:items}=await db.rpc("claim_outreach_items",{p_user_id:userId,p_run_id:runId,p_limit:50});
 for(const item of items??[]){ const row=item as {id:string;prospect_id:string;channel:"email"|"voice";scheduled_for:string}; try { const {data:lead}=await db.from("prospects").select("lead_status").eq("id",row.prospect_id).eq("user_id",userId).maybeSingle(); if(!lead||["engaged","qualified","disqualified","converted","do_not_contact"].includes(String(lead.lead_status))){await db.from("outreach_run_items").update({status:"cancelled",skip_reason:"lead_no_longer_eligible",completed_at:new Date().toISOString()}).eq("id",row.id).eq("user_id",userId);continue} if(row.channel==="voice"){ const outcome=await startQualificationCall({userId,leadId:row.prospect_id,consentConfirmed:true,approvalId:String(run.approval_id),scheduledFor:row.scheduled_for,idempotencyKey:`item:${row.id}:voice`,source:"dispatcher"}); await db.from("outreach_run_items").update({status:outcome.status==="already_called"?"skipped":"scheduled",voice_execution_id:outcome.executionId,skip_reason:outcome.status==="already_called"?"already_called_person":null,completed_at:new Date().toISOString()}).eq("id",row.id).eq("user_id",userId); if(outcome.status!=="already_called") await emitState(db,userId,row.prospect_id,"call_queued",runId) } else { await queueEmail(db,userId,runId,row.prospect_id,row.id); await emitState(db,userId,row.prospect_id,"email_queued",runId) } } catch(e){ await db.from("outreach_run_items").update({status:"failed",error:e instanceof Error?e.message:"dispatch_failed"}).eq("id",row.id).eq("user_id",userId) } }
 const {data:all}=await db.from("outreach_run_items").select("status").eq("run_id",runId).eq("user_id",userId); const completed=(all??[]).filter(x=>["queued","scheduled","completed"].includes(String(x.status))).length,failed=(all??[]).filter(x=>x.status==="failed").length,skipped=(all??[]).filter(x=>["skipped","cancelled"].includes(String(x.status))).length,active=(all??[]).some(x=>["pending","claimed"].includes(String(x.status))); await db.from("outreach_runs").update({status:active?"running":failed?"partial":"completed",completed_count:completed,failed_count:failed,skipped_count:skipped,completed_at:active?null:new Date().toISOString()}).eq("id",runId).eq("user_id",userId)
}
async function queueEmail(db:ReturnType<typeof createAdminClient>,userId:string,runId:string,prospectId:string,itemId:string){ const {data:mailbox}=await db.from("mailboxes").select("id").eq("user_id",userId).eq("status","active").maybeSingle(); const {data:lead}=await db.from("prospects").select("email,email_subject,email_body").eq("id",prospectId).eq("user_id",userId).single(); if(!mailbox||!lead?.email) throw new Error(!mailbox?"missing_active_mailbox":"missing_email"); const {data:campaign}=await db.from("campaigns").insert({user_id:userId,mailbox_id:mailbox.id,name:`Autonomous outreach ${runId}`,status:"active"}).select("id").single(); const {data:recipient,error}=await db.from("campaign_recipients").insert({campaign_id:campaign!.id,user_id:userId,prospect_id:prospectId,email:lead.email,subject:lead.email_subject??"Quick question",body:lead.email_body??"",status:"scheduled",scheduled_for:new Date().toISOString()}).select("id").single(); if(error||!recipient) throw new Error(error?.message??"email_queue_failed"); await db.from("outreach_run_items").update({status:"queued",campaign_recipient_id:recipient.id,completed_at:new Date().toISOString()}).eq("id",itemId).eq("user_id",userId) }
async function emitState(db:ReturnType<typeof createAdminClient>,userId:string,prospectId:string,event:ProspectEvent,sourceId:string){await applyProspectTransition(db,{userId,prospectId,event,actor:"system",source:"outreach_run",sourceId})}
