"use client";

import { useEffect, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { callNowFromHandoff, queueCustomEmailFromHandoff, scheduleEmailFollowupFromHandoff, updateHandoffStatus, updateLeadFromHandoff } from "@/app/app/inbox/handoff-actions";

export interface HandoffCardItem { id: string; prospectId: string; leadName: string; company: string | null; sourceType: string; reason: string; priority: string; summary: string; recommendedNextAction: string; dueAt: string | null; createdAt: string; status: string; }
function CallNowDialog({ id }: { id: string }) { const [confirmed, setConfirmed] = useState(false); const [pending, start] = useTransition(); return <Dialog><DialogTrigger render={<Button size="sm">Call now</Button>} /><DialogContent><DialogHeader><DialogTitle>Confirm call</DialogTitle><DialogDescription>Call Now still enforces consent, DNC/suppression, calling hours, E.164 validation, and the one-call guard.</DialogDescription></DialogHeader><label className="flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} />I confirm I have lawful permission to call this prospect.</label><DialogFooter><Button disabled={!confirmed || pending} onClick={() => start(() => { void callNowFromHandoff(id, confirmed); })}>Confirm and call</Button></DialogFooter></DialogContent></Dialog>; }
function EmailDialog({ id }: { id: string }) { const [subject, setSubject] = useState(""); const [body, setBody] = useState(""); const [pending, start] = useTransition(); return <Dialog><DialogTrigger render={<Button size="sm" variant="outline">Send custom email</Button>} /><DialogContent><DialogHeader><DialogTitle>Queue custom email</DialogTitle><DialogDescription>The message is queued through the owned Gmail outbox and remains subject to send-time compliance checks.</DialogDescription></DialogHeader><Input placeholder="Subject" value={subject} onChange={(event) => setSubject(event.target.value)} /><Textarea placeholder="Write a tailored response" value={body} onChange={(event) => setBody(event.target.value)} /><DialogFooter><Button disabled={!subject.trim() || !body.trim() || pending} onClick={() => start(() => { void queueCustomEmailFromHandoff(id, subject, body); })}>Queue email</Button></DialogFooter></DialogContent></Dialog>; }
function FollowupDialog({ id }: { id: string }) { const [scheduledAt, setScheduledAt] = useState(""); const [timezone, setTimezone] = useState(Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC"); const [note, setNote] = useState(""); const [pending, start] = useTransition(); return <Dialog><DialogTrigger render={<Button size="sm" variant="outline">Schedule follow-up</Button>} /><DialogContent><DialogHeader><DialogTitle>Schedule email follow-up</DialogTitle><DialogDescription>Voice follow-ups require the existing chat approval flow. This action schedules a tenant-owned email follow-up.</DialogDescription></DialogHeader><Input type="datetime-local" value={scheduledAt} onChange={(event) => setScheduledAt(event.target.value)} /><Input value={timezone} onChange={(event) => setTimezone(event.target.value)} placeholder="IANA timezone" /><Textarea placeholder="Internal note (optional)" value={note} onChange={(event) => setNote(event.target.value)} /><DialogFooter><Button disabled={!scheduledAt || !timezone || pending} onClick={() => start(() => { void scheduleEmailFollowupFromHandoff(id, new Date(scheduledAt).toISOString(), timezone, note); })}>Schedule</Button></DialogFooter></DialogContent></Dialog>; }
export function HandoffCards({ items }: { items: HandoffCardItem[] }) {
  const [pending, start] = useTransition();
  const router = useRouter();
  // Bounded fallback where Realtime publication is not configured. Cleanup prevents
  // background refreshes after unmount and server rendering safely escapes summaries.
  useEffect(() => { const timer = window.setInterval(() => router.refresh(), 30_000); return () => window.clearInterval(timer); }, [router]);
  if (!items.length) return null;
  const invoke = (work: () => Promise<unknown>) => start(() => { void work(); });
  return <section className="mb-6 space-y-3"><h2 className="text-base font-semibold">Actionable handoffs</h2>{items.map((item) => <Card key={item.id} className="border-amber-500/30"><CardContent className="p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">{item.leadName}{item.company ? ` · ${item.company}` : ""}</p><p className="text-xs text-muted-foreground">{item.reason.replaceAll("_", " ")} · {item.sourceType.replaceAll("_", " ")} · {item.priority} priority{item.dueAt ? ` · due ${new Date(item.dueAt).toLocaleString()}` : ""}</p></div><span className="rounded bg-amber-500/15 px-2 py-1 text-xs capitalize text-amber-600">{item.status}</span></div><p className="mt-3 whitespace-pre-wrap text-sm">{item.summary}</p><p className="mt-2 text-sm font-medium">Suggested: {item.recommendedNextAction}</p><div className="mt-3 flex flex-wrap gap-2"><CallNowDialog id={item.id} /><EmailDialog id={item.id} /><FollowupDialog id={item.id} /><Button size="sm" variant="outline" disabled={pending} onClick={() => invoke(() => updateLeadFromHandoff(item.id, "converted"))}>Mark converted</Button><Button size="sm" variant="outline" disabled={pending} onClick={() => invoke(() => updateLeadFromHandoff(item.id, "disqualified"))}>Mark disqualified</Button><Button size="sm" variant="ghost" disabled={pending} onClick={() => invoke(() => updateHandoffStatus(item.id, "resolved"))}>Resolve</Button><Button size="sm" variant="ghost" disabled={pending} onClick={() => invoke(() => updateHandoffStatus(item.id, "dismissed"))}>Dismiss</Button></div></CardContent></Card>)}</section>;
}