NEXT_API_ROUTES = [
    {"path": "/api/analytics", "method": "GET", "migration": "later"},
    {"path": "/api/auth/callback", "method": "GET", "migration": "keep-next-for-oauth"},
    {"path": "/api/chat", "method": "POST", "migration": "last"},
    {"path": "/api/cron/advance-sequences", "method": "GET", "migration": "phase-3"},
    {"path": "/api/cron/detect-replies", "method": "GET", "migration": "phase-3"},
    {"path": "/api/cron/poll-intent", "method": "GET", "migration": "phase-3"},
    {"path": "/api/cron/run-automations", "method": "GET", "migration": "phase-3"},
    {"path": "/api/cron/send-due", "method": "GET", "migration": "phase-3"},
    {"path": "/api/domain-check", "method": "POST", "migration": "phase-2"},
    {"path": "/api/export/csv", "method": "GET", "migration": "phase-4"},
    {"path": "/api/export/sheets", "method": "POST", "migration": "phase-4"},
    {"path": "/api/extension/alerts", "method": "GET", "migration": "phase-2"},
    {"path": "/api/extension/me", "method": "GET", "migration": "phase-1"},
    {"path": "/api/extension/push-register", "method": "POST", "migration": "phase-2"},
    {
        "path": "/api/extension/replies/{id}/draft-response",
        "method": "POST",
        "migration": "phase-5",
    },
    {"path": "/api/extension/replies/{id}/handle", "method": "POST", "migration": "phase-2"},
    {"path": "/api/extension/web-push-key", "method": "GET", "migration": "phase-2"},
    {"path": "/api/extension/web-push-subscribe", "method": "POST", "migration": "phase-2"},
    {"path": "/api/health", "method": "GET", "migration": "phase-1"},
    {"path": "/api/inngest", "method": "GET/POST/PUT", "migration": "phase-3-or-replace"},
    {"path": "/api/mailbox/callback", "method": "GET", "migration": "keep-next-for-oauth"},
    {"path": "/api/mailbox/connect", "method": "GET", "migration": "keep-next-for-oauth"},
    {"path": "/api/prospects/{id}", "method": "PATCH", "migration": "phase-2"},
    {"path": "/api/webhooks/razorpay", "method": "POST", "migration": "phase-3"},
    {"path": "/api/webhooks/stripe", "method": "POST", "migration": "phase-3"},
    {"path": "/api/webhooks/whatsapp", "method": "GET/POST", "migration": "phase-3"},
]


PYTHON_ROUTES = [
    {"path": "/api/health", "method": "GET", "status": "implemented", "framework": "django"},
    {"path": "/health", "method": "GET", "status": "implemented", "framework": "django"},
    {"path": "/api/extension/me", "method": "GET", "status": "implemented", "framework": "django"},
    {"path": "/api/migration/routes", "method": "GET", "status": "implemented", "framework": "django"},
    {"path": "/api/domain-check", "method": "GET", "status": "implemented", "framework": "django"},
    {"path": "/api/extension/alerts", "method": "GET", "status": "implemented", "framework": "django"},
    {"path": "/api/extension/push-register", "method": "POST", "status": "implemented", "framework": "django"},
    {"path": "/api/extension/replies/{id}/handle", "method": "POST", "status": "implemented", "framework": "django"},
    {"path": "/api/extension/web-push-key", "method": "GET", "status": "implemented", "framework": "django"},
    {"path": "/api/extension/web-push-subscribe", "method": "POST", "status": "implemented", "framework": "django"},
    {"path": "/api/prospects/{id}", "method": "PATCH", "status": "implemented", "framework": "django"},
    {"path": "/api/export/csv", "method": "GET", "status": "implemented", "framework": "django"},
    {"path": "/api/export/sheets", "method": "POST", "status": "implemented", "framework": "django"},
    {"path": "/api/webhooks/stripe", "method": "POST", "status": "implemented", "framework": "django"},
    {"path": "/api/webhooks/razorpay", "method": "POST", "status": "implemented", "framework": "django"},
    {"path": "/api/webhooks/whatsapp", "method": "GET/POST", "status": "implemented", "framework": "django"},
    {"path": "/api/cron/send-due", "method": "GET/POST", "status": "implemented", "framework": "django"},
    {"path": "/api/cron/detect-replies", "method": "GET/POST", "status": "implemented", "framework": "django"},
    {"path": "/api/cron/poll-intent", "method": "GET/POST", "status": "implemented", "framework": "django"},
    {"path": "/api/cron/advance-sequences", "method": "GET/POST", "status": "implemented", "framework": "django"},
    {"path": "/api/cron/run-automations", "method": "GET/POST", "status": "implemented", "framework": "django"},
]
